### ISSUE TITLE
jdbc  sql 脱敏

### ISSUE THREAD

**Issue by songlonqi-java** [GuanceCloud/opentelemetry-java-instrumentation#15]
链路数据中展示的 sql 语句都已经将参数替换成了 `?` ，导致客户排查问题时有困难。

ddtrace已经支持了。

**Comment by songlonqi-java** [comment]
在链路中的字段是 db.statement 也就是原始的 sql 语句。

**Comment by lrwh** [comment]
> 在链路中的字段是 db.statement 也就是原始的 sql 语句。


otel 是支持的，你可以测试下


## 数据库脱敏

agent 在设置 `db.statement` 语义属性之前清理所有数据库查询/语句。查询字符串中的所有值（字符串、数字）都替换为问号 ( ?)。

注意：JDBC 绑定参数不会在`db.statement`. 如果您正在寻找捕获绑定参数，请参阅[issue](https://github.com/open-telemetry/opentelemetry-java-instrumentation#7413)相应的问题。

例子：

- SQL 查询`SELECT a from b where password="secret"`将出现 `SELECT a from b where password=?`在导出的跨度中；
- Redis 命令`HSET map password "secret"`将出现 `HSET map password ?`在导出的跨度中。

默认情况下，所有数据库检测都启用此行为。使用以下属性禁用它：

系统属性： otel.instrumentation.common.db-statement-sanitizer.enabled
环境变量： OTEL_INSTRUMENTATION_COMMON_DB_STATEMENT_SANITIZER_ENABLED
默认值：true
说明：启用 DB 语句清理。

**Comment by songlonqi-java** [comment]
脱敏问题其实是写法的问题 

比如 ：
```java
    ps = conn.prepareStatement("SELECT name,password,id FROM student where name=? and password=?");
    ps.setString(1,username);   // set   替换第一个？
    ps.setString(2,pw);        //  替换第二个？
```

这是jdbc的写法 如库无关（oracle和mysql都是这么写的）。

这种写法 agent 拿到的就是 两个？ 的 resource。

另一种写法
```java
    ps = conn.prepareStatement("SELECT name,password,id FROM student where name='guance' and password='123456'");
   // ps.setString(1,username);  不再使用 set
   // ps.setString(2,pw);
```

这时候 探针 拿到的就是 不带问号的sql语句。

上面说的 `OTEL_INSTRUMENTATION_COMMON_DB_STATEMENT_SANITIZER_ENABLED` 是作用与这里的。


究其原因，是因为 agent 的探针 是在函数 `prepareStatement` 上。 代码是
```java
 transformer.applyAdviceToMethod(
        nameStartsWith("execute").and(takesArgument(0, String.class)).and(isPublic()),
        StatementInstrumentation.class.getName() + "$StatementAdvice");
```

从根本上解决脱敏问题。需要加探针加在 set 上。set 在先 将参数缓存，之后才是 exectue() , 将缓存参数放到 Attributes中。

**Comment by songlonqi-java** [comment]
新增命令行参数：`-Dotel.jdbc.sql.obfuscation=true`  或者环境变量 `OTEL_JDBC_SQL_OBFUSCATION=true`

**Comment by songlonqi-java** [comment]
#16 Merge 

close issue
